### ISSUE TITLE
Cannot create a project without a repository

### ISSUE THREAD

**Issue by santiagofm** [xmartlabs/rnx-cli#12]
### Current behavior

I want to create a project without specifying a repository:

- Run `npx @xmartlabs/rnx-cli i MyAwesomeProject`.
- Choose `No` when asked about adding a repository.
- Errors out with an error message: `Error adding pre-push hooks.`.

### Expected behavior

I should be able to create a project without specifying a repository:

- Run `npx @xmartlabs/rnx-cli i MyAwesomeProject`.
- Choose `No` when asked about adding a repository.
- The CLI should continue on without a repo.

### Video Reproduction

<img src="https://user-images.githubusercontent.com/6749415/199554546-2f883aad-4b7d-4854-b483-9c7370948814.gif" width="400" />

### Platform

- [ ] Windows
- [X] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| node                                   |  v14.19.1 
| yarn                            |  1.22.15

**Comment by nicoache1** [comment]
HI @santiagofm it should be working in the latest version. Please check out, im going to close the issue but feel free to open it again if its not really solved
